# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.heraglobaltech.com
title: Hera Global Tech
email: bradyasheehan@gmail.com
author: Brady Sheehan
description: > # "Write an awesome description for your new site here. 
  Hera Global Tech is a biotechnology company with a focus on personal health and safety solutions
  using cutting edge sensors and machine learning technologies.
copyright: 'Copyright &copy; 2018 Hera Global Tech, inc. All Rights Reserved.'
# credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/hera_globaltech
  - title: linkedin
    url: https://www.linkedin.com/company/13463389/
